version: '3.1'

services:
  redis:
    image: redis
    container_name: redis
    restart: always
    network_mode: host
    ports:
      - 6379:6379
    volumes:
        - '/storage/docker/redis/redis.conf:/usr/local/etc/redis/redis.conf'
