apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: ks-k8s
spec:
  hosts:
    - {name: admin, address: 9.135.90.159, internalAddress: 9.135.90.159, port: 36000, user: root, password: "123"}
    - {name: gpu-node1, address: 9.135.117.186, internalAddress: 9.135.117.186, port: 36000, user: root, password: "123"}
  roleGroups:
    etcd:
      - admin
    control-plane:
      - admin
    worker:
      - admin
      - gpu-node1
  controlPlaneEndpoint:
      ## Internal loadbalancer for apiservers
      # internalLoadbalancer: haproxy

      domain: lb.kubesphere.local
      address: ""
      port: 6443
    kubernetes:
      version: v1.23.17
      clusterName: cluster.local
      autoRenewCerts: true
      containerManager: docker
    etcd:
      type: kubekey
    network:
      plugin: calico
      kubePodsCIDR: 10.233.64.0/18
      kubeServiceCIDR: 10.233.0.0/18
      ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
      multusCNI:
        enabled: false
    registry:
      privateRegistry: ""
      namespaceOverride: ""
      registryMirrors: []
      insecureRegistries: []
    addons: []
