version: '3.1'

services:
  redis:
    image: rstudio/rstudio-server-pro
    container_name: rstudio
    restart: always
    network_mode: host
    volumes:
        - './rstudio:/home/rstudio'
    command: sh /home/rstudio/docker-entrypoint.sh
