version: '3.1'

services:
  rstudio:
    image: rstudio/rstudio-server-pro
    container_name: rstudio
    restart: always
    network_mode: host
    volumes:
      - './data:/data'
    command:
      - "sh /usr/local/bin/startup.sh"
      - "sh /data/docker-entrypoint.sh"
