version: '3.1'

services:
  rstudio:
    image: rocker/rstudio
    container_name: rstudio
    restart: always
    # network_mode: host
    ports:
      - "8787:8787"
    volumes:
      - "./data:/home/rstudio"
    environment:
      TZ: "Asia/Shanghai"
      PASSWORD: "rstudio"
      ROOT: "TRUE"
      # DISABLE_AUTH: "true"
    privileged: true
