version: '3.1'

services:
  redis:
    image: rstudio/rstudio-server-pro
    container_name: rstudio
    restart: always
    network_mode: host
    volumes:
        - './data:/data'
    entrypoint: "sh /data/docker-entrypoint.sh"
