version: '3.1'

services:
  rstudio-server-pro:
    # image: rstudio/rstudio-server-pro
    build: .
    container_name: rstudio
    restart: always
    network_mode: host
    volumes:
      - './data:/home/rstudio/data'
