kind: RoleBinding 
apiVersion: rbac.authorization.k8s.io/v1 
metadata:   
 name: gitlab-admin 
 namespace: gitlab
subjects: 
- kind: ServiceAccount   
  name: default
  namespace: gitlab 
roleRef:   
 kind: ClusterRole   
 name: admin   
 apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: gitlab
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["*"]
---
kind: ClusterRoleBinding 
apiVersion: rbac.authorization.k8s.io/v1 
metadata:   
 name: gitlab
subjects: 
- kind: ServiceAccount   
  name: default
  namespace: gitlab 
roleRef:   
 kind: ClusterRole   
 name: gitlab
 apiGroup: rbac.authorization.k8s.io
