hadoop_version: '3.2.0'
hadoop_home: '{{ hadoop_install_dir }}/{{ hadoop_pkg_name }}'
hadoop_conf_dir: '{{ hadoop_home }}/etc/hadoop'
hadoop_tmp_dir: '{{ hadoop_home }}/tmp'

pkg_name: 'hadoop-{{ hadoop_version }}'
pkg_url: 'https://apache.org/dist/hadoop/core/stable/{{ hadoop_pkg_name }}.tar.gz'
pkg_install_dir: '/usr/local/cnt'

dfs_nameservice: 'ns1'
dfs_edits_dir: '{{ hadoop_home }}/journal/data'
dfs_ha_enabled: true
dfs_failover_provider: 'org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider'
dfs_ha_fencing_methods:
- 'sshfence'
- 'shell(/bin/true)'
dfs_ha_fencing_pkfiles: '/root/.ssh/id_rsa'
dfs_ha_fencing_timeout: 30000

mapreduce_framework_name: 'yarn'

yarn_ha_enabled: true
yarn_rm_cluster_id: 'yrc'
yarn_aux_services: 'mapreduce_shuffle'

local_pkg_path: '{{ local_pkg_dir }}/{{ pkg_name }}.tar.gz'

home:
- name: 'HADOOP_HOME'
  path: '{{ hadoop_home }}'
  exports:
  - 'bin'
  - 'sbin'
