version: '3.3'

services:
  git:
    image: gogs/gogs
    container_name: gogs
    ports:
        - '10022:22/tcp'
        - '10080:3000/tcp'
    volumes:
        - '/var/docker/gogs/data:/data'
    restart: always
