version: '3.3'

services:
  dns:
    image: sameersbn/bind
    container_name: bind
    ports:
        - '53:53/tcp'
        - '53:53/udp'
        - '10000:10000/tcp'
    volumes:
        - '/var/docker/bind/data:/data'
    restart: always
