
services:
  dns:
    image: sameersbn/bind:9.16.1-20200524
    container_name: bind
    ports:
        - '53:53/tcp'
        - '53:53/udp'
        - '10000:10000/tcp'
    volumes:
        - '/data/bind:/data'
    restart: always
    environment:
        WEBMIN_INIT_SSL_ENABLED: false
