apiVersion: v1
kind: Secret
metadata:
  name: registry-key
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImVtaGhiMmh4T0RJNE9scElVVUF5TUNFMmFIVnpkQT09IgoJCX0sCgkJInF1YXkuaW8iOiB7CgkJCSJhdXRoIjogImVtaGhiMmh4T2xwSVVVQXlNQ0UyYUhWemRBPT0iCgkJfSwKCQkicmVnaXN0cnkuY250LmlvIjogewoJCQkiYXV0aCI6ICJZV1J0YVc0NmFHRnlZbTl5UURVeE16TT0iCgkJfQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE4LjA5LjEgKGxpbnV4KSIKCX0KfQ==
