services:
  tf-gpu:
    image: tensorflow/tensorflow:2.4.3-gpu-jupyter
    #command: python
    restart: always
    ports:
      - 8888:8888
    volumes:
      - "./tf:/tf"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              #device_ids: ['0', '3']
              capabilities: [gpu]
