apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: 192.168.88.120:6443
#etcd:
#  external:
#    endpoints:
#    - "http://192.168.88.120:2379"
#    - "http://192.168.88.121:2379"
#    - "http://192.168.88.122:2379"
networking:
  #serviceSubnet: 10.96.0.0/12
  podSubnet: 10.244.0.0/16
  #dnsDomain: cluster.local
imageRepository: registry.aliyuncs.com/google_containers
