#apiVersion: kubeadm.k8s.io/v1beta1
#kind: ClusterConfiguration
#kubernetesVersion: stable
#controlPlaneEndpoint: 192.168.88.120:6443
#etcd:
#  external:
#    endpoints:
#    - "http://192.168.88.120:2379"
#    - "http://192.168.88.121:2379"
#    - "http://192.168.88.122:2379"
#networking:
  #serviceSubnet: 10.96.0.0/12
  #podSubnet: 10.244.0.0/16
  #dnsDomain: cluster.local
#imageRepository: registry.aliyuncs.com/google_containers


apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: c5gs62.kbw74dtv0re2o11r
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 172.16.0.10
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: vm-0-10-centos
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: 127.0.0.1:6443
controllerManager: {}
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.aliyuncs.com/google_containers
kind: ClusterConfiguration
kubernetesVersion: v1.20.0
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
scheduler: {}
