version: '3.1'

services:

  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.2.0
    restart: always
    ports:
      - 28080:8080
    volumes:
        - '/storage/docker/xxl-job-admin/applogs:/data/applogs'
    environment:
      PARAMS: '--spring.datasource.url=jdbc:mysql://172.19.0.2:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai 
               --spring.datasource.username=root 
               --spring.datasource.password=root'

