apiVersion: v1
kind: PersistentVolume
metadata:
  name: nacos-mysql-master
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "nacos-mysql"
    path: "nacos-mysql-master"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nacos-mysql-slave
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "nacos-mysql"
    path: "nacos-mysql-slave"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacos-mysql-master
  namespace: nacos
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: nacos-mysql-master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacos-mysql-slave
  namespace: nacos
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: nacos-mysql-slave
