apiVersion: v1
kind: PersistentVolume
metadata:
  name: dind
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "gitlab-runner"
    path: "runner/docker"
    readOnly: false
