- name: include tasks of repo-RedHat.yml
  include_tasks: 'roles/common/tasks/repo-RedHat.yml'

- name: disable selinux
  selinux: state=disabled

- name: ensure br_netfilter kernel module is loaded
  modprobe: name=br_netfilter state=present

- name: check /proc/sys/net/bridge/bridge-nf-call-iptables
  command: cat /proc/sys/net/bridge/bridge-nf-call-iptables
  register: bridge_nf
  changed_when: false

- debug: var=bridge_nf

- name: ensure /proc/sys/net/bridge/bridge-nf-call-iptables is set to 1
  shell: 'echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables'
  when: bridge_nf.stdout == '0'

- name: include tasks of swapoff
  include_tasks: roles/common/tasks/swapoff.yml
