version: "3.7"

services:
  pulsar:
    image: apachepulsar/pulsar
    command: bin/pulsar standalone
    hostname: pulsar
    ports:
      - "6650:6650"
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./data:/pulsar/data
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    networks:
      - network_pulsar

  dashboard:
    image: "apachepulsar/pulsar-manager"
    hostname: pulsar-manager
    ports:
      - "9527:9527"
      - "7750:7750"
    depends_on:
      - pulsar
    links:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
    networks:
      - network_pulsar

  redis:
    image: "redislabs/redistimeseries"
    hostname: redistimeseries
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
      - PYTHONUNBUFFERED=1
    networks:
      - network_pulsar

  alertmanager:
    image: prom/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    hostname: redistimeseries
    ports:
      - "9093:9093"
    restart: always
    volumes:
      - ./alertmanager:/alertmanager
    networks:
      - network_pulsar

  prometheus:
    image: prom/prometheus
    hostname: redistimeseries
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - network_pulsar

  grafana:
    image: streamnative/apache-pulsar-grafana-dashboard
    hostname: redistimeseries
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - prometheus
    environment:
      PULSAR_CLUSTER: "standalone"
      # export PULSAR_PROMETHEUS_URL=http://$(ifconfig|grep "inet "|grep -v 127.0.0.1|head -1|awk '{ print $2 }'):9090
      PULSAR_PROMETHEUS_URL: ${PULSAR_PROMETHEUS_URL} # http://10.43.58.81:9090
    networks:
      - network_pulsar

networks:
  network_pulsar:
    name: network_pulsar
    driver: bridge