apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  labels:
    name: pv01
spec:
  nfs:
    path: /nfs/volume/v1
    server: 192.168.88.125
  accessModes: ["ReadWriteMany", "ReadWriteOnce"]
  capacity:
    storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv02
  labels:
    name: pv02
spec:
  nfs:
    path: /nfs/volume/v2
    server: 192.168.88.125
  accessModes: ["ReadWriteMany"]
  capacity:
    storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv03
  labels:
    name: pv03
spec:
  nfs:
    path: /nfs/volume/v3
    server: 192.168.88.125
  accessModes: ["ReadWriteMany", "ReadWriteOnce"]
  storageClassName: standard
  capacity:
    storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv04
  labels:
    name: pv04
spec:
  nfs:
    path: /nfs/volume/v4
    server: 192.168.88.125
  accessModes: ["ReadWriteMany", "ReadWriteOnce"]
  storageClassName: standard
  capacity:
    storage: 15Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv05
  labels:
    name: pv05
spec:
  nfs:
    path: /nfs/volume/v5
    server: 192.168.88.125
  accessModes: ["ReadWriteMany", "ReadWriteOnce"]
  storageClassName: standard
  capacity:
    storage: 20Gi
