---
- hosts: cnt
  remote_user: root

  roles:
  - role: java
    tags:
    - java
  - role: zookeeper
    when: inventory_hostname in groups.zk
    tags:
    - zk
  - role: hadoop
    when: inventory_hostname in groups.hadoop
    tags:
    - hadoop
