---
- hosts: cnt
  remote_user: root

  roles:
  - role: java
    tags:
    - java
  - role: scala
    when: inventory_hostname in groups.spark
    tags:
    - scala
  - role: zookeeper
    when: inventory_hostname in groups.zk
    tags:
    - zk
  - role: hadoop
    when: inventory_hostname in groups.hadoop
    tags:
    - hadoop
  - role: spark
    when: inventory_hostname in groups.spark
    tags:
    - spark
  - role: docker
    when: inventory_hostname in groups.k8s
    tags:
    - docker
  - role: kubernetes
    when: inventory_hostname in groups.k8s
    tags:
    - k8s
