version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
        - '/var/docker/mysql/etc/conf.d:/etc/mysql/conf.d'
        - '/var/docker/mysql/var/lib:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 38080:8080
