zk_version: '3.4.14'
zk_home: '{{ pkg_install_dir }}/{{ pkg_name }}'
zk_conf_dir: '{{ zk_home }}/conf'
zk_conf_path: '{{ zk_conf_dir }}/zoo.cfg'
zk_data_dir: '{{ zk_home }}/data'

pkg_name: 'zookeeper-{{ zk_version }}'
pkg_url: 'https://apache.org/dist/zookeeper/stable/{{ pkg_name }}.tar.gz'
pkg_install_dir: '/usr/local/cnt'

local_pkg_path: '{{ local_pkg_dir }}/{{ pkg_name }}.tar.gz'

home:
- name: 'ZK_HOME'
  path: '{{ zk_home }}'
  exports:
  - 'bin'
