java_version: '1.8.0_212'
java_home: '{{ pkg_install_dir }}/jdk{{ java_version }}'

pkg_name: 'jdk-8u212-linux-x64.tar.gz'
pkg_url: 'https://apache.org/dist/zookeeper/stable/{{ pkg_name }}'
pkg_install_dir: '/usr/local/java'

local_pkg_path: '{{ local_pkg_dir }}/{{ pkg_name }}'

home:
- name: 'JAVA_HOME'
  path: '{{ java_home }}'
  exports:
  - 'bin'